---

- name: restart exim4
  become: yes
  service:
    name: exim4
    state: restarted

- name: restart monit
  become: yes
  service:
    name: monit
    state: restarted

- name: restart ssh
  service:
    name: ssh
    state: restarted
